config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  get '/callback', to: 'users#callback'
  get '/authenticate', to: 'users#authenticate'
  get '/logout', to: 'users#logout'

  resources :gists

  get 'starred/gists', to: 'gists#index_starred'
end

app/models/gist.rb
class Gist
  include ActiveModel::Model, ActiveModel::Validations
  attr_accessor :description, :files, :id
  attr_reader :public

  validates_presence_of :description
  validate :files_not_empty

  def initialize(args = { description: '', files: [] })
    @description = args[:description] || ''
    @files = args[:files] || []
    @public = false
  end

  private def files_not_empty
    if !files || files.size === 0
      self.errors[:files] << 'Must contain atleast one file.'
    else
      with_content = files.select { |file| !file[:content].blank? && !file[:name].blank? }

      if with_content.size === 0
        self.errors[:files] << 'Files must have name and content.'
      end
    end
  end
end

app/controllers/application_controller.rb
require 'octokit'

class ApplicationController < ActionController::Base
  helper_method :authenticated?
  
  def authenticated?
    session[:access_token]
  end

  def get_client
    client = Octokit::Client.new(
      :client_id => ENV['CLIENT_ID'],
      :client_secret => ENV['CLIENT_SECRET']
    )

    valid = client.check_application_authorization(session[:access_token])

    if !valid
      return nil
    end

    client = Octokit::Client.new(
      :access_token => session[:access_token]
    )
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :check_auth_status

  def index
    if @client
      @gists = @client.gists.select { |gist| gist.public === false }
    end
  end

  def index_starred
    if @client
      @gists = @client.starred_gists.select { |gist| gist.public === false }
    end

    @path = '/gists'
    render :index
  end

  def show
    id = params[:id]

    begin
      gist = @client.gist(id)
      @description = gist.description
      @url = gist.html_url
      @commits = @client.gist_commits(id)
    rescue
      flash.now[:error] = 'No commits found matching provided gist Id.'
    end
  end

  def new
    @gist = Gist.new
  end

  def edit
    id = params[:id]

    if !id.blank?
      gist = @client.gist(id)

      if gist
        @gist = Gist.new(
          :description => gist.description,
          :public => gist.public,
          :files => gist.files.fields.map { |key| { name: key, content: gist.files[key][:content] }}
        )

        @gist.id = gist.id
      end
    end
  end

  def create
    @gist = Gist.new(gist_params)

    if @gist.valid?

      begin
        @client.create_gist({
          :description => @gist.description,
          :public => @gist.public,
          :files => Hash[@gist.files.map { |file| [file[:name], { content: file[:content] }] }]
        })
      rescue
        flash[:error] = 'There was an error creating a new gist.'
      end

      redirect_to action: 'index'
      return
    end

    @path = '/gists/new'
    render :new
  end

  def update
    id = params[:id]

    if id
      @gist = Gist.new(gist_params)
      gist = @client.gist(id)

      if !gist.blank? && @gist.valid?

        begin
          @client.edit_gist(gist.id, {
            :description => @gist.description,
            :public => @gist.public,
            :files => Hash[@gist.files.map { |file| [file[:name], { content: file[:content] }] }]
          })
        rescue
          flash[:error] = 'There was an error editing the gist.'
        end

        redirect_to action: 'index', :flash => flash
        return
      end
    end

    render :edit
  end

  def destroy
    id = params[:id]
    gist = @client.gist(id)

    if gist
      deleted = @client.delete_gist(gist.id)
      
      if !deleted.blank?
        flash.now[:error] = 'There was an error deleting the gist. Ensure you have sufficient permissions.'
      end
    else
      flash.now[:error] = 'Gist with provided Id was not found.'
    end

    redirect_to action: 'index'
  end

  private
    def check_auth_status
      if authenticated?
        client = get_client

        if client
          @client = client
          return
        end
      end
      
      redirect_to root_path
    end

    def gist_params
      params.require(:gist).permit(:description, :files => [ :name, :content ])
    end
end

app/controllers/users_controller.rb
require 'octokit'

class UsersController < ApplicationController
  def index
    if authenticated?
      client = get_client

      if client
        @name = client.user.name
      end
    end
  end

  def authenticate
    # Provide a state string key for cross-site protection
    session[:state] = SecureRandom.base64

    client = Octokit::Client.new

    url = client.authorize_url(ENV['CLIENT_ID'],
      :scope => ENV['CLIENT_SCOPE'],
      :state => session[:state],
    )

    redirect_to url
  end

  def callback
    code = request.query_parameters[:code]
    state = request.query_parameters[:state]

    if code && state
      if (request.query_parameters[:state] != session[:state])
        redirect_to root_path
        return
      end

      result = Octokit.exchange_code_for_token(code, ENV['CLIENT_ID'], ENV['CLIENT_SECRET'])
      access_token = result[:access_token]

      if access_token
        session[:access_token] = access_token
      end
    end

    redirect_to action: 'index'
  end

  def logout
    session[:access_token] = nil
    redirect_to root_path
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gists/_delete_file_modal.html.erb
<div class="modal fade delete-file-modal" id="DeleteFileModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        Are you sure you want to delete the gist?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary delete-callback">Yes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>

app/views/gists/_single_gist_form.html.erb
<%= form_for @gist, :url => {:action => locals[:action] }, :method => locals[:method] || 'post', :html => { :class => 'gist-form my-4', :id => "gist-#{locals[:action]}" } do |f| %>
  <% if @gist.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      Please correct errors below and try to again.
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <div class="form-group my-4 p-y2">
  <%= f.text_field :description, :class => "form-control col-sm-12 col-md-6", :placeholder => 'Gist description' %>
    <% if !@gist.errors[:description].blank? %>
      <small class="text-sm text-danger float-left mb-2">
        Please provide a description.
      </small>
    <% end %>
  </div>
  <div class="files-container">
    <% if @gist.files.size > 0 %>
      <% @gist.files.each_with_index do |file, index|%>
        <div class="form-group my-4" id="file-<%= index %>">
          <%= text_field_tag '[gist]files[][name]', file[:name], :class => 'form-control my-2', :placeholder => 'File name with extension' %>
          <%= text_area_tag '[gist]files[][content]', file[:content], :class => 'form-control my-2', :placeholder => 'Code', :rows => 5 %>
          <button class="delete-file-button btn btn-sm float-right btn-danger mb-4" type="button">
            Delete File
          </button>
        </div>
      <% end %>
    <% else %>
      <div class="form-group my-4">
        <%= text_field_tag '[gist]files[][name]', '', :class => 'form-control my-2', :placeholder => 'File name with extension' %>
        <%= text_area_tag '[gist]files[][content]', '', :class => 'form-control my-2', :placeholder => 'Code', :rows => 5 %>
        <button class="delete-file-button btn btn-sm float-right btn-danger mb-4" type="button">
          Delete File
        </button>
      </div>
    <% end %>
  </div>
  <% if !@gist.errors[:files].blank? %>
    <small class="text-left my-2 text-danger d-block">
      Atleast one file with name and code content is required.
    </small>
  <% end %>
  <button type="button" class="add-file-button btn btn-info btn-sm float-left">
    Add File
  </button>
  <%= f.submit locals[:submit_label], :class => 'btn btn-primary' %>
<% end %>

app/views/gists/_view_commit_changes_modal.html.erb
<div class="modal fade view-commit-changes-modal" id="ViewCommitChangesModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/gists/edit.html.erb
<%= render 'layouts/inner_content' do %>
  <% if @gist %>
    <%= render 'single_gist_form', locals: { :action => 'update', :method => 'patch', :submit_label => 'Edit Gist' } %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>Note:</strong> Files missing name or code content will be skipped.
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% else %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      A Gist with provided Id was no found
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>

app/views/gists/index.html.erb
<%= render 'layouts/inner_content' do %>
  <% if flash[:error] %>
    <div class="alert alert-danger alert-dismissible fade show mt-4" role="alert">
      <%= flash[:error] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <div class="dropdown show mt-4 text-right">
    <button class="btn btn-outline-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Filter
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
       <%= link_to 'All', gists_path, class: 'dropdown-item' %>
       <%= link_to 'Starred', '/starred/gists', class: 'dropdown-item' %>
    </div>
  </div>
  <% if @gists.size > 0 %>
    <div class="table-responsive">
      <table class="gist-list table my-4">
        <thead class="thead-light">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Url</th>
            <th scope="col">Description</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @gists.each_with_index do |gist, index| %>
          <tr>
            <th scope="row"><%= index+1 %></th>
            <td>
              <%= link_to 'Link', gist.html_url, target: :_blank %>
            </td>
            <td>
              <%= gist.description %>
            </td>
            <td>
              <%= link_to 'Edit', edit_gist_path(id: gist.id), class: 'btn btn-sm btn-outline-info' %>
            </td>
            <td>
              <%= link_to 'View history',
                gist_path(id: gist.id),
                class: 'btn btn-sm btn-outline-secondary'
              %>
            </td>
            <td>
              <%= link_to 'Delete',
                gist_path(id: gist.id),
                method: 'delete',
                class: 'delete-gist-button btn btn-sm btn-outline-danger',
                data: { toggle: 'modal', target: '#DeleteFileModal' }
              %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <h6>No Gists Found</h6>  
  <% end %>
<% end %>
<%= render 'delete_file_modal' %>

app/views/gists/new.html.erb
<%= render 'layouts/inner_content' do %>
  <%= render 'single_gist_form', locals: { action: 'create', submit_label: 'Create Gist' } %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Note:</strong> Files missing name or code content will be skipped.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/gists/show.html.erb
<%= render 'layouts/inner_content' do %>
  <% if flash[:error] %>
    <div class="alert alert-danger alert-dismissible fade show mt-4" role="alert">
      <%= flash[:error] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <div class="gist-info mt-2 text-left">
    Description: <%= @description %><br>
    Url: <%= link_to @url, @url, target: :_blank %>
  </div>
  <div class="table-responsive">
    <table class="commit-list table my-4">
      <thead class="thead-light">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Details</th>
          <th scope="col">Change Stats</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @commits.each_with_index do |commit, index| %>
        <tr>
          <th scope="row"><%= index+1 %></th>
          <td class="text-left">
            Version: <%= commit.version %><br>
            Committed At:  <%= commit.committed_at %>
          </td>
          <td>
            Additions: <%= commit.change_status.additions %><br>
            Deletions: <%= commit.change_status.deletions %><br>
            Total:  <%= commit.change_status.total %>
          </td>
          <td>
            <input type="hidden" value="<%= commit.url %>" id="<%= commit.version %>">
            <%= link_to 'View Files',
              '#',
              class: "view-commit-changes btn btn-sm btn-outline-success"
            %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>
<%= render 'view_commit_changes_modal' %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "SnippetMan", root_path, class: "navbar-brand" %>
    <% if authenticated? %>
      <%= link_to "Logout", logout_path, class: "btn btn-sm btn-outline-secondary" %>
    <% end %>
  </div>
</nav>

app/views/layouts/_inner_content.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-12 p-5 text-center">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link #{current_page?('/') ? 'active': ''}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Private Gists", gists_path, class: "nav-link #{current_page?('/gists') || @path === '/gists' ? 'active': ''}" %>
        </li>
        <li class="nav-item">
          <%=
            link_to "Create Private Gist",
            new_gist_path,
            class: "nav-link #{current_page?('/gists/new') || @path === '/gists/new' ? 'active': ''}"
          %>
        </li>
      </ul>
      <%= yield %>
    </div>
  </div>
</div>

app/views/layouts/_loading_spinner.html.erb
<div class="spinner modal" id="Spinner">
  <div class="modal-dialog-centered">
    <div class="sk-fading-circle">
      <div class="sk-circle1 sk-circle"></div>
      <div class="sk-circle2 sk-circle"></div>
      <div class="sk-circle3 sk-circle"></div>
      <div class="sk-circle4 sk-circle"></div>
      <div class="sk-circle5 sk-circle"></div>
      <div class="sk-circle6 sk-circle"></div>
      <div class="sk-circle7 sk-circle"></div>
      <div class="sk-circle8 sk-circle"></div>
      <div class="sk-circle9 sk-circle"></div>
      <div class="sk-circle10 sk-circle"></div>
      <div class="sk-circle11 sk-circle"></div>
      <div class="sk-circle12 sk-circle"></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnippetMan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
    <%= render partial: 'layouts/loading_spinner' %>
  </body>
</html>

app/views/users/index.html.erb
<%if authenticated? %>
  <%= render 'layouts/inner_content' do %>
    <h6 class="p-2 my-2">Welcome <%= @name.titleize %>!</h6>
  <% end %>
<%else%>
  <div class="container">
    <div class="row">
      <div class="col col-xs-12 p-5 text-center">
        <%= link_to "Authenticate with Github", authenticate_path, class: "btn btn-info" %>
      </div>
    </div>
  </div>
<%end%>